### ISSUE TITLE
Add X-Plane 11 OBJ directives - NORMAL_METALNESS, BLEND_GLASS

### ISSUE THREAD

**Issue by tngreene** [der-On/XPlane2Blender#260]
Blender should take advantage of the new OBJ header directives in Blender!

What is needed:
- [ ] Edit [OBJ spec](http://developer.x-plane.com/?article=obj8-file-format-specification) to include new material from the [X-Plane 11 new material model article](http://developer.x-plane.com/?article=x-plane-11-material-model)
- [x] Create Blender UI to enable and opt-in to this
- [x] Tie it into the existing exporter model
- [x] Make validations for it
    1. [x] BLEND_GLASS only legal on aircraft/cockpit/panel objects
    2. [x] NORMAL_METALNESS flag must match in all the cases where normal TEXTURE choice must match
    3. [x] NORMAL_METALNESS flag must meet additional [requirerments](https://github.com/der-On/XPlane2Blender/issues/260#issuecomment-309801820)
    4. [x] Like others: 2 materials used for the same purpose must match having their textures
    5. [x] The scene settings must be >= X-Plane 11
- [x] Make unit tests for BLEND_GLASS (see [here](https://github.com/der-On/XPlane2Blender/issues/260#issuecomment-310225867))
- [x] Make unit tests for NORMAL_METALNESS (see [here](https://github.com/der-On/XPlane2Blender/issues/260#issuecomment-310380990) and [here](https://github.com/der-On/XPlane2Blender/issues/260#issuecomment-310384396))
- [ ] Document it in the [wiki](https://github.com/der-On/XPlane2Blender/wiki/Material-Property-Matrix)

**Comment by tngreene** [comment]
Created UI features for this. 22f9d91055a29bab7420716f5149bd4f91a933eb

**Comment by tngreene** [comment]
Exporter tie in for BLEND_GLASS: c3091a5ed2caa820e87c09d48a089150aa20f3ae

**Comment by bsupnik** [comment]
Per our discussion on Skype: when NORMAL_METALNESS is in use.
- The header should contain GLOBAL_specular 1.0
- NO ATTR_shiny_rat or GLOBAL_specular should be written at all based on user set material shininess.
- Illegal differences in user material shininess should be ignored.

**Comment by tngreene** [comment]
Exporter tie for NORMAL_METALNESS: b5325c90999

**Comment by tngreene** [comment]
Validation for BLEND_GLASS 56513e290c68c68ce063

**Comment by bsupnik** [comment]
TEST CASES FOR BLEND_GLASS:
[ ] Export cockpit object with blend glass enabled on the material, confirm BLEND_GLASS is in the OBJ header of the fixture.
[ ] Export aircraft object with two materials, one BLEND_GLASS and one not.  Confirm validation failure (conflict of blend glass status on materials).
[ ] Export scenery object with BLEND_GLASS enabled, confirm validation fails (BLEND_GLASS illegao for scenery).
[ ] Export instanced scenery object with BLEND_GLASS enabled, confirm validation fails (BLEND_GLASS illegal for scenery).

**Comment by bsupnik** [comment]
TEST CASES FOR NORMAL_METALNESS (basic usage):
Matrix 1 (directive present):
- Normal metalness on vs off
- Draped material present vs not.
- Non-draped material present vs not.
This represents 8 test cases (2x2x2).  Note that for no draped and no non-draped material present, this can be done with an OBJect that contains only one lamp.

In this case, the NORMAL_METALNESS needs to appear after the TEXTURE directive for each of the draped and non-draped materials.

Matrix 2 (specularity):
- NORMAL_METALNESS present vs not - when present specularity is controlled by a single GLOBAL_specular 1.0 directive in the header and the model is ignored.  When it is not, we get legacy behavior
- export scenery instanced vs scenery
- export with one material (with a shiny ratio) vs two

This forms another 8-way test case (2x2x2).  Note that ONE case should fail: scenery instanced with two specularity-materials and NO normal-metalness should fail validation due to conflicting specular in a scenery-instanced object. This is the ONLY case that should fail to export of the 8.

**Comment by bsupnik** [comment]
MATRIX 3: DRAPED specularity (scenery export type)
- Normal metalness vs not
- One draped material vs two (each has its OWN specularity)
In this case the non-metal two material draped export is the only failing case.

**Comment by tngreene** [comment]
Thought of another test: Create a blend file, set version to XP11, enable new features, switch it back to XP10, make sure that they don't show up in the OBJ. Ensuring everything is guarded by if version >= 1100.

**Comment by tngreene** [comment]
Matrix 1 table (in ASCII Table)

 ```
type = [none|non_metal|metal]
D_[type]_NON_D_[type]
                                             Non-Draped
                               None  |         Non-Metal          | Metal
D             ---------------------------------------------------------------------------
r  None      |D_none_NON_D_none     |D_none_NON_D_non_metal      |D_none_NON_D_metal     |
a            |----------------------|----------------------------|-----------------------|
p  Non-Metal |D_non_metal_NON_D_none|D_non_metal_NON_D_non_metal |D_non_metal_NON_D_metal|
e            |----------------------|----------------------------|-----------------------|
d  Metal     |D_metal_NON_D_none    |D_metal_NON_D_non_metal     |D_metal_NON_D_metal    |
              ---------------------------------------------------------------------------
Recommended order
1. D_none_NON_D_non_metal
2. D_none_NON_D_metal
3. D_non_metal_NON_D_non_metal
4. D_non_metal_NON_D_metal
5. Anything from row 3

```

**Comment by tngreene** [comment]
Matrix 1 committed and pushed! 659845b1593f5ab0636004711013170a836cbc09

**Comment by tngreene** [comment]
Every test case created, debugged, passing, unbroken, broken, rebroken properly, thrown over the fence, dragged through a lake, and all round finished or I'll throw my hat into a volcano, closed!

956ca757e39ac946174e2a0a02d503970518b2df

**Comment by tngreene** [comment]
So..... it turns out that this wasn't well and truely finished. Blend Glass was supposed to be a boolean, not another options for Blend Mode, blend_v1100 was a bad idea, Normal Metaless had its own problems with not enough validations.

See commits between 7/15/2018-8/1/2018. Also see #353, #357, #363, and #368
